import Head from "next/head";
import styles from "../styles/pages/About.module.scss";

export default function () {
  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.About}>
        <h1>About Us</h1>
        <p className={styles.description}>
          Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eos incidunt
          soluta eaque, ut aliquid in suscipit architecto, atque, maiores
          molestiae aspernatur! Praesentium quis maxime provident quidem
          repudiandae eum sequi ad. Ratione, perspiciatis assumenda eligendi
          quas labore facere provident nam. Aspernatur beatae, nam corrupti a
          sed laborum mollitia velit vitae quas.
        </p>
      </div>
    </>
  );
}
