import Head from "next/head";
import Header from "@/components/Header";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <h1>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus,
        ducimus, eum dolorem tenetur repellendus dicta obcaecati beatae iusto,
        blanditiis veritatis facere quod harum. Iure ducimus ad minima quos,
        accusamus pariatur neque quo fuga corrupti exercitationem deleniti,
        consequatur porro nesciunt tempore excepturi esse delectus voluptate?
        Porro veniam iusto autem, esse laborum est illo quasi impedit recusandae
        aperiam consequatur doloribus rem repellendus ipsa adipisci odit sequi
        facilis error dolorum fugiat nobis delectus consequuntur! Libero ratione
        laudantium minus repellendus obcaecati reprehenderit molestiae dolorem
        facilis officia eius beatae ad odit recusandae incidunt, natus excepturi
        nostrum officiis, aliquid quis saepe unde perferendis voluptas.
        Molestias, cupiditate.
      </h1>
    </>
  );
}
