import { useRouter } from "next/router";
import Head from "next/head";
import Card from "../../components/Card";
import { roomList } from "../../mocks/reservations.js";
import styles from "./index.module.scss";

export default function () {
  const router = useRouter();

  const onHandleClick = (id) => router.push(`/locations/${id}`);

  return (
    <>
      <Head>
        <title>Locations</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.Locations}>
        {roomList?.map((item) => (
          <Card
            key={item.id}
            data={item}
            onHandleClick={onHandleClick}
            type="locations"
          />
        ))}
      </div>
    </>
  );
}
